#!/usr/bin/env python3
"""Derive tests/fixtures/openapi/ from the platform's docs/api specs.

Usage:
    python scripts/snapshot_openapi_schemas.py <specs_dir> <out_dir> --source-commit <SHA>

The wire-shape contract (tests/test_wire_shape.py) reads exactly one thing
from each spec: for every schema under ``components.schemas``, the names of
its ``properties``. This script writes that and nothing else, one output file
per input ``*.yaml``, under the same file name:

    components:
      schemas:
        <SchemaName>:
          properties:
            <field>: {}

It drops:
    - every schema without a non-empty ``properties`` mapping, which the
      contract's loader skips anyway;
    - descriptions, types, examples, paths and the ``info`` block. The
      platform specs carry the platform's own licence statement there, and
      this repository is MIT (tests/test_license_metadata.py).

Output is deterministic (sorted keys, fixed header), so re-running it on the
same input is byte-identical, and a change in the snapshot is a change in the
platform's schemas.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any

import yaml


def derive(doc: dict[str, Any]) -> dict[str, Any]:
    """Return the schema-and-property-names view of one OpenAPI document."""
    schemas = (doc.get("components") or {}).get("schemas") or {}
    kept: dict[str, Any] = {}
    for name, schema in schemas.items():
        if not isinstance(schema, dict):
            continue
        props = schema.get("properties")
        if not isinstance(props, dict) or not props:
            continue
        kept[name] = {"properties": {field: {} for field in props}}
    return {"components": {"schemas": kept}}


def render(source_name: str, source_bytes: bytes, commit: str, derived: dict[str, Any]) -> str:
    """Render a derived document with the header naming where it came from."""
    digest = hashlib.sha256(source_bytes).hexdigest()
    header = (
        "# GENERATED by scripts/snapshot_openapi_schemas.py - do not edit.\n"
        f"# Source: docs/api/{source_name} at platform commit {commit}\n"
        f"# Source sha256: {digest}\n"
        "# Schema names and property names only; see tests/fixtures/openapi/README.md.\n"
    )
    return header + yaml.safe_dump(derived, sort_keys=True, default_flow_style=False)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "specs_dir", type=Path, help="directory holding the platform's docs/api *.yaml"
    )
    parser.add_argument("out_dir", type=Path, help="directory to write the derived files into")
    parser.add_argument(
        "--source-commit", required=True, help="platform commit the specs were taken from"
    )
    args = parser.parse_args(argv)

    sources = sorted(args.specs_dir.glob("*.yaml"))
    if not sources:
        print(f"no *.yaml files in {args.specs_dir}", file=sys.stderr)
        return 1
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for src in sources:
        raw = src.read_bytes()
        doc = yaml.safe_load(raw) or {}
        out = args.out_dir / src.name
        out.write_text(render(src.name, raw, args.source_commit, derive(doc)), encoding="utf-8")
        kept = len(derive(doc)["components"]["schemas"])
        print(f"{src.name}: {kept} schemas with properties -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
