"""AxonFlow Python SDK - Enterprise AI Governance in 3 Lines of Code.

This SDK provides a simple, async-first interface for integrating AI governance
into your Python applications. It supports policy enforcement, audit logging,
MCP connectors, and multi-agent planning.

Example:
    >>> from axonflow import AxonFlow
    >>>
    >>> # Async usage
    >>> async with AxonFlow(
    ...     endpoint="https://your-agent.axonflow.com",
    ...     client_id="your-client-id",
    ...     client_secret="your-client-secret"
    ... ) as client:
    ...     result = await client.proxy_llm_call("user-token", "What is AI?", "chat")
    ...     print(result.data)
    >>>
    >>> # Sync usage
    >>> client = AxonFlow.sync(
    ...     endpoint="https://your-agent.axonflow.com",
    ...     client_id="your-client-id",
    ...     client_secret="your-client-secret"
    ... )
    >>> result = client.proxy_llm_call("user-token", "What is AI?", "chat")
"""

from axonflow._version import __version__
from axonflow.authzen import (
    AUTHZEN_ATTRIBUTE_MARKER,
    AUTHZEN_PATH,
    AUTHZEN_PROFILE_HEADER,
    AUTHZEN_PROTOCOL_DECISION_STATE_DISAGREEMENT,
    AUTHZEN_PROTOCOL_MISSING_PROFILE_CONTEXT,
    AUTHZEN_PROTOCOL_OBLIGATIONS_ON_REFUSAL,
    AUTHZEN_PROTOCOL_STRUCTURE_TOO_DEEP,
    AUTHZEN_PROTOCOL_UNDECODABLE_BODY,
    AUTHZEN_PROTOCOL_UNKNOWN_OPERATIONAL_STATE,
    AUTHZEN_PROTOCOL_UNRESOLVED_ATTRIBUTE,
    AUTHZEN_PROTOCOL_UNSPECIFIED,
    AUTHZEN_PROTOCOL_UNSUPPORTED_PROFILE,
    AUTHZEN_UNKNOWN_CLOSURE_TRUNCATED,
    AUTHZEN_UNKNOWN_CLOSURE_UNAVAILABLE,
    AUTHZEN_UNKNOWN_MALFORMED_VALUE,
    AUTHZEN_UNKNOWN_NOT_SUPPLIED,
    AUTHZEN_UNKNOWN_REQUIRED_ABSENT,
    AUTHZEN_UNKNOWN_RESOLUTION_FAILED,
    AUTHZEN_UNKNOWN_SCHEMA_MISMATCH,
    AUTHZEN_UNKNOWN_STALE,
    AuthZENAttribute,
    AuthZENAttributeState,
    AuthZENDecision,
    AuthZENProtocolError,
    AuthZENProtocolErrorKind,
    AuthZENRefusal,
    AuthZENRefusedBy,
    AuthZENTransport,
    build_envelope,
    to_wire,
)
from axonflow.authzen_types_gen import *  # noqa: F403 - see the __all__ note at the foot of this file
from axonflow.authzen_types_gen import __all__ as _AUTHZEN_GENERATED_NAMES
from axonflow.client import (
    AxonFlow,
    HealthResponse,
    PlatformCapability,
    SDKCompatibility,
    SyncAxonFlow,
)
from axonflow.code_governance import (
    CodeFile,
    CodeGovernanceMetrics,
    ConfigureGitProviderRequest,
    ConfigureGitProviderResponse,
    CreatePRRequest,
    CreatePRResponse,
    ExportOptions,
    ExportResponse,
    FileAction,
    GitProviderInfo,
    GitProviderType,
    ListGitProvidersResponse,
    ListPRsOptions,
    ListPRsResponse,
    PRRecord,
    ValidateGitProviderRequest,
    ValidateGitProviderResponse,
)
from axonflow.exceptions import (
    AuthenticationError,
    AxonFlowError,
    BudgetExceededError,
    ConfigurationError,
    ConnectionError,
    ConnectorError,
    IdempotencyKeyMismatchError,
    ObligationNotFulfillableError,
    PlanExecutionError,
    PolicyViolationError,
    RateLimitError,
    TimeoutError,
    VersionConflictError,
)
from axonflow.execution import (
    ExecutionStatus,
    ExecutionStatusValue,
    ExecutionType,
    StepStatusValue,
    UnifiedApprovalStatus,
    UnifiedGateDecision,
    UnifiedListExecutionsRequest,
    UnifiedListExecutionsResponse,
    UnifiedStepStatus,
    UnifiedStepType,
)
from axonflow.hitl import (
    HITLApprovalRequest,
    HITLQueueListOptions,
    HITLQueueListResponse,
    HITLReviewInput,
    HITLStats,
)
from axonflow.masfeat import (
    # Types
    AISystemRegistry,
    # Enums
    AISystemUseCase,
    FEATAssessment,
    FEATAssessmentStatus,
    FEATPillar,
    Finding,
    FindingSeverity,
    FindingStatus,
    KillSwitch,
    KillSwitchEvent,
    KillSwitchEventType,
    KillSwitchStatus,
    MaterialityClassification,
    RegistrySummary,
    SystemStatus,
)
from axonflow.pep import (
    CONTENT_TYPE_TEXT,
    DECIDE_PATH,
    OBLIGATION_REDACT_PII,
    PHASE_REQUEST,
    PHASE_RESPONSE,
    REQUEST_REDACTION_PATH,
    RESPONSE_REDACTION_PATH,
    VERDICT_ALLOW,
    VERDICT_DENY,
    VERDICT_NEEDS_APPROVAL,
    has_request_redaction,
)
from axonflow.policies import (
    CreateDynamicPolicyRequest,
    CreatePolicyOverrideRequest,
    CreateStaticPolicyRequest,
    DynamicPolicy,
    DynamicPolicyAction,
    DynamicPolicyCondition,
    EffectivePoliciesOptions,
    ListDynamicPoliciesOptions,
    ListStaticPoliciesOptions,
    OverrideAction,
    PolicyAction,
    PolicyCategory,
    PolicyOverride,
    PolicySeverity,
    PolicyTier,
    PolicyVersion,
    StaticPolicy,
    TestPatternMatch,
    TestPatternResult,
    UpdateDynamicPolicyRequest,
    UpdateStaticPolicyRequest,
)
from axonflow.telemetry import register_adapter
from axonflow.types import (
    CATEGORY_MEDIA_BIOMETRIC,
    CATEGORY_MEDIA_DOCUMENT,
    CATEGORY_MEDIA_PII,
    CATEGORY_MEDIA_SAFETY,
    TRANSFER_BASIS_ADEQUACY,
    TRANSFER_BASIS_CONSENT,
    TRANSFER_BASIS_PASAL_56B_DPA,
    TRANSFER_BASIS_SAFEGUARDS,
    AuditLogEntry,
    AuditQueryOptions,
    AuditResult,
    AuditSearchRequest,
    AuditSearchResponse,
    AuditToolCallRequest,
    AuditToolCallResponse,
    AxonFlowConfig,
    Budget,
    BudgetAlert,
    BudgetAlertsResponse,
    BudgetCheckRequest,
    BudgetDecision,
    BudgetInfo,
    BudgetOnExceed,
    BudgetPeriod,
    BudgetScope,
    BudgetsResponse,
    BudgetStatus,
    CacheConfig,
    CancelPlanResponse,
    CircuitBreakerConfig,
    CircuitBreakerConfigUpdate,
    CircuitBreakerHistoryEntry,
    CircuitBreakerHistoryResponse,
    CircuitBreakerStatusResponse,
    ClientRequest,
    ClientResponse,
    CodeArtifact,
    ConnectorHealthStatus,
    ConnectorInstallRequest,
    ConnectorMetadata,
    ConnectorPolicyInfo,
    ConnectorResponse,
    CreateBudgetRequest,
    DecideRequest,
    DecideResponse,
    DecisionCallerIdentity,
    DecisionTarget,
    DynamicPolicyInfo,
    DynamicPolicyMatch,
    ExecutionDetail,
    ExecutionExportOptions,
    ExecutionMode,
    ExecutionSnapshot,
    ExecutionSummary,
    ExfiltrationCheckInfo,
    ExplainPolicy,
    # Policy Simulation types (Evaluation Tier+)
    ImpactReportInput,
    ImpactReportRequest,
    ImpactReportResponse,
    ImpactReportResult,
    ListBudgetsOptions,
    ListExecutionsOptions,
    ListExecutionsResponse,
    ListUsageRecordsOptions,
    ListWebhooksResponse,
    LLMProvider,
    LLMProviderHealth,
    LLMProviderListResponse,
    MCPCheckInputRequest,
    MCPCheckInputResponse,
    MCPCheckOutputRequest,
    MCPCheckOutputResponse,
    MediaAnalysisResponse,
    MediaAnalysisResult,
    MediaContent,
    MediaGovernanceConfig,
    MediaGovernanceStatus,
    Mode,
    ModelPricing,
    Obligation,
    ObligationFulfillment,
    PaginationMeta,
    PlanExecutionResponse,
    PlanResponse,
    PlanStep,
    PlanVersionEntry,
    PlanVersionsResponse,
    PolicyApprovalResult,
    PolicyConflict,
    PolicyConflictRef,
    PolicyConflictResponse,
    PolicyEvaluationInfo,
    PolicyEvaluationResult,
    PolicyMatchInfo,
    PricingInfo,
    PricingListResponse,
    RateLimitInfo,
    ResumePlanResponse,
    RetryConfig,
    RollbackPlanResponse,
    SimulatePoliciesRequest,
    SimulatePoliciesResponse,
    SimulationDailyUsage,
    TimelineEntry,
    TokenUsage,
    TransferBasis,
    UpdateBudgetRequest,
    UpdateMediaGovernanceConfigRequest,
    UpdatePlanRequest,
    UpdatePlanResponse,
    UsageBreakdown,
    UsageBreakdownItem,
    UsageRecord,
    UsageRecordsResponse,
    UsageSummary,
    WebhookSubscription,
)
from axonflow.workflow import (
    AbortWorkflowRequest,
    ApprovalStatus,
    ApproveStepResponse,
    CreateWorkflowRequest,
    CreateWorkflowResponse,
    GateDecision,
    ListWorkflowsOptions,
    ListWorkflowsResponse,
    MarkStepCompletedRequest,
    PendingApproval,
    PendingApprovalsResponse,
    PolicyMatch,
    PriorCompletionStatus,
    RejectStepResponse,
    RetryContext,
    RetryPolicy,
    StepGateRequest,
    StepGateResponse,
    StepType,
    ToolContext,
    WorkflowSource,
    WorkflowStatus,
    WorkflowStatusResponse,
    WorkflowStepInfo,
)

__all__ = [
    # Version
    "__version__",
    # Telemetry — declaring a framework adapter on the existing heartbeat.
    # See axonflow.telemetry.register_adapter; it performs no I/O.
    "register_adapter",
    # Main client
    "AxonFlow",
    "SyncAxonFlow",
    # Version discovery types
    "PlatformCapability",
    "SDKCompatibility",
    "HealthResponse",
    # Configuration
    "AxonFlowConfig",
    "Mode",
    "RetryConfig",
    "CacheConfig",
    # Request/Response types
    "ClientRequest",
    "ClientResponse",
    "PolicyEvaluationInfo",
    "CodeArtifact",
    # Multimodal Image Governance types
    "MediaContent",
    "MediaAnalysisResult",
    "MediaAnalysisResponse",
    # Media Governance Config types
    "MediaGovernanceConfig",
    "MediaGovernanceStatus",
    "UpdateMediaGovernanceConfigRequest",
    # Media Governance Category constants
    "CATEGORY_MEDIA_SAFETY",
    "CATEGORY_MEDIA_BIOMETRIC",
    "CATEGORY_MEDIA_DOCUMENT",
    "CATEGORY_MEDIA_PII",
    # Connector types
    "ConnectorMetadata",
    "ConnectorInstallRequest",
    "ConnectorResponse",
    "ConnectorHealthStatus",
    "ConnectorPolicyInfo",
    # MCP Policy Check types
    "ExplainPolicy",
    "MCPCheckInputRequest",
    "MCPCheckInputResponse",
    "MCPCheckOutputRequest",
    "MCPCheckOutputResponse",
    # Decision Mode PEP contract (ADR-056, #2563)
    "DecideRequest",
    "DecideResponse",
    "DecisionCallerIdentity",
    "DecisionTarget",
    "Obligation",
    "ObligationFulfillment",
    "ObligationNotFulfillableError",
    "OBLIGATION_REDACT_PII",
    "PHASE_REQUEST",
    "PHASE_RESPONSE",
    "CONTENT_TYPE_TEXT",
    "VERDICT_ALLOW",
    "VERDICT_DENY",
    "VERDICT_NEEDS_APPROVAL",
    "DECIDE_PATH",
    "REQUEST_REDACTION_PATH",
    "RESPONSE_REDACTION_PATH",
    "has_request_redaction",
    # Planning types
    "PlanStep",
    "PlanResponse",
    "PlanExecutionResponse",
    "PolicyEvaluationResult",
    # MAP v1.0 types
    "ExecutionMode",
    "CancelPlanResponse",
    "UpdatePlanRequest",
    "UpdatePlanResponse",
    "PlanVersionEntry",
    "PlanVersionsResponse",
    "ResumePlanResponse",
    "VersionConflictError",
    # Gateway Mode types
    "RateLimitInfo",
    "PolicyApprovalResult",
    "PolicyMatchInfo",
    "ExfiltrationCheckInfo",
    "DynamicPolicyMatch",
    "DynamicPolicyInfo",
    "TokenUsage",
    "AuditResult",
    # Audit Log Read types (Issue #878)
    "AuditSearchRequest",
    "AuditSearchResponse",
    "AuditLogEntry",
    "AuditQueryOptions",
    # Cross-border transfer basis (UU PDP Pasal 56)
    "TransferBasis",
    "TRANSFER_BASIS_ADEQUACY",
    "TRANSFER_BASIS_SAFEGUARDS",
    "TRANSFER_BASIS_PASAL_56B_DPA",
    "TRANSFER_BASIS_CONSENT",
    # Audit Tool Call types (Issue #1260)
    "AuditToolCallRequest",
    "AuditToolCallResponse",
    # Policy Simulation types (Evaluation Tier+)
    "SimulatePoliciesRequest",
    "SimulatePoliciesResponse",
    "SimulationDailyUsage",
    "ImpactReportInput",
    "ImpactReportRequest",
    "ImpactReportResult",
    "ImpactReportResponse",
    "PolicyConflictRef",
    "PolicyConflict",
    "PolicyConflictResponse",
    # Circuit Breaker Observability types (Issue #1176)
    "CircuitBreakerStatusResponse",
    "CircuitBreakerHistoryEntry",
    "CircuitBreakerHistoryResponse",
    "CircuitBreakerConfig",
    "CircuitBreakerConfigUpdate",
    # Execution Replay types
    "ExecutionSummary",
    "ExecutionSnapshot",
    "ExecutionDetail",
    "TimelineEntry",
    "ListExecutionsOptions",
    "ListExecutionsResponse",
    "ExecutionExportOptions",
    # Policy CRUD types
    "PolicyCategory",
    "PolicyTier",
    "PolicyAction",
    "PolicySeverity",
    "OverrideAction",
    "StaticPolicy",
    "DynamicPolicy",
    "PolicyOverride",
    "PolicyVersion",
    "DynamicPolicyAction",
    "DynamicPolicyCondition",
    "TestPatternResult",
    "TestPatternMatch",
    "ListStaticPoliciesOptions",
    "ListDynamicPoliciesOptions",
    "EffectivePoliciesOptions",
    "CreateStaticPolicyRequest",
    "UpdateStaticPolicyRequest",
    "CreateDynamicPolicyRequest",
    "UpdateDynamicPolicyRequest",
    "CreatePolicyOverrideRequest",
    # Code Governance types (Enterprise)
    "GitProviderType",
    "FileAction",
    "CodeFile",
    "ConfigureGitProviderRequest",
    "ConfigureGitProviderResponse",
    "ValidateGitProviderRequest",
    "ValidateGitProviderResponse",
    "GitProviderInfo",
    "ListGitProvidersResponse",
    "CreatePRRequest",
    "CreatePRResponse",
    "PRRecord",
    "ListPRsOptions",
    "ListPRsResponse",
    "CodeGovernanceMetrics",
    "ExportOptions",
    "ExportResponse",
    # AuthZEN-native authorization (ADR-065) — the HAND-WRITTEN half. The wire
    # types and enum constants are generated and appended to __all__ below.
    # AUTHZEN_ATTRIBUTE_MARKER is exported because it is what a caller needs to
    # hand-build an attribute on the far side of a boundary the objects cannot
    # cross - a queue, a worker, a cache that round-trips through JSON. That is
    # the case the marker exists for, so withholding it left the mechanism
    # documented and unusable. The sibling TypeScript SDK exports it too.
    "AUTHZEN_ATTRIBUTE_MARKER",
    "AUTHZEN_PATH",
    "AUTHZEN_PROFILE_HEADER",
    "AUTHZEN_PROTOCOL_DECISION_STATE_DISAGREEMENT",
    "AUTHZEN_PROTOCOL_MISSING_PROFILE_CONTEXT",
    "AUTHZEN_PROTOCOL_OBLIGATIONS_ON_REFUSAL",
    "AUTHZEN_PROTOCOL_STRUCTURE_TOO_DEEP",
    "AUTHZEN_PROTOCOL_UNDECODABLE_BODY",
    "AUTHZEN_PROTOCOL_UNKNOWN_OPERATIONAL_STATE",
    "AUTHZEN_PROTOCOL_UNRESOLVED_ATTRIBUTE",
    "AUTHZEN_PROTOCOL_UNSPECIFIED",
    "AUTHZEN_PROTOCOL_UNSUPPORTED_PROFILE",
    "AUTHZEN_UNKNOWN_CLOSURE_TRUNCATED",
    "AUTHZEN_UNKNOWN_CLOSURE_UNAVAILABLE",
    "AUTHZEN_UNKNOWN_MALFORMED_VALUE",
    "AUTHZEN_UNKNOWN_NOT_SUPPLIED",
    "AUTHZEN_UNKNOWN_REQUIRED_ABSENT",
    "AUTHZEN_UNKNOWN_RESOLUTION_FAILED",
    "AUTHZEN_UNKNOWN_SCHEMA_MISMATCH",
    "AUTHZEN_UNKNOWN_STALE",
    "AuthZENAttribute",
    "AuthZENAttributeState",
    "AuthZENDecision",
    "AuthZENProtocolError",
    "AuthZENProtocolErrorKind",
    "AuthZENRefusal",
    "AuthZENRefusedBy",
    "AuthZENTransport",
    "build_envelope",
    "to_wire",
    # Exceptions
    "AxonFlowError",
    "ConfigurationError",
    "AuthenticationError",
    "PolicyViolationError",
    "RateLimitError",
    "BudgetExceededError",
    "ConnectionError",
    "TimeoutError",
    "ConnectorError",
    "IdempotencyKeyMismatchError",
    "PlanExecutionError",
    # Cost Controls types
    "BudgetScope",
    "BudgetPeriod",
    "BudgetOnExceed",
    "BudgetInfo",
    "CreateBudgetRequest",
    "UpdateBudgetRequest",
    "ListBudgetsOptions",
    "LLMProvider",
    "LLMProviderHealth",
    "LLMProviderListResponse",
    "PaginationMeta",
    "Budget",
    "BudgetsResponse",
    "BudgetStatus",
    "BudgetAlert",
    "BudgetAlertsResponse",
    "BudgetCheckRequest",
    "BudgetDecision",
    "UsageSummary",
    "UsageBreakdownItem",
    "UsageBreakdown",
    "ListUsageRecordsOptions",
    "UsageRecord",
    "UsageRecordsResponse",
    "ModelPricing",
    "PricingInfo",
    "PricingListResponse",
    # Workflow Control Plane types
    "WorkflowStatus",
    "WorkflowSource",
    "GateDecision",
    "ApprovalStatus",
    "StepType",
    "RetryPolicy",
    "CreateWorkflowRequest",
    "CreateWorkflowResponse",
    "StepGateRequest",
    "StepGateResponse",
    "RetryContext",
    "PriorCompletionStatus",
    "WorkflowStepInfo",
    "WorkflowStatusResponse",
    "ListWorkflowsOptions",
    "ListWorkflowsResponse",
    "MarkStepCompletedRequest",
    "AbortWorkflowRequest",
    "PolicyMatch",
    "ToolContext",
    # WCP Approval types (Feature 5)
    "ApproveStepResponse",
    "RejectStepResponse",
    "PendingApproval",
    "PendingApprovalsResponse",
    # Plan Rollback types (Feature 7)
    "RollbackPlanResponse",
    # Webhook types (Feature 7)
    "WebhookSubscription",
    "ListWebhooksResponse",
    # MAS FEAT Compliance types (Enterprise)
    "FindingSeverity",
    "FindingStatus",
    "Finding",
    "MaterialityClassification",
    "SystemStatus",
    "FEATAssessmentStatus",
    "KillSwitchStatus",
    "FEATPillar",
    "AISystemUseCase",
    "KillSwitchEventType",
    "AISystemRegistry",
    "RegistrySummary",
    "FEATAssessment",
    "KillSwitch",
    "KillSwitchEvent",
    # HITL Queue API types (Enterprise)
    "HITLApprovalRequest",
    "HITLQueueListOptions",
    "HITLQueueListResponse",
    "HITLReviewInput",
    "HITLStats",
    # Unified Execution types (Issue #1075)
    "ExecutionType",
    "ExecutionStatusValue",
    "StepStatusValue",
    "UnifiedStepType",
    "UnifiedGateDecision",
    "UnifiedApprovalStatus",
    "UnifiedStepStatus",
    "ExecutionStatus",
    "UnifiedListExecutionsRequest",
    "UnifiedListExecutionsResponse",
]

# The AuthZEN wire types, enum constants and profile identifiers are GENERATED
# from the platform's canonical surface artifact (scripts/gen_authzen_types.py),
# and are appended here rather than transcribed into the literal above. A
# hand-maintained list would be a second transcription of the artifact — the
# exact drift the generator exists to prevent — and it would silently leave a
# newly-added error code unreachable from `axonflow` while four other SDKs had
# it. Regenerating the types is all it takes for the public surface to follow.
__all__ += list(_AUTHZEN_GENERATED_NAMES)
